server:
  port: 8087
spring:
  application:
    name: monitor-client
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
turbine:
  app-config: boss-feign
  cluster-name-expression: new String("default")
  combine-host-port: true